const constants = {
  CREATE_ENTRY_REQUEST: "CREATE_ENTRY_REQUEST",
  CREATE_ENTRY_SUCCESS: "CREATE_ENTRY_SUCCESS",
  CREATE_ENTRY_ERRORS: "CREATE_ENTRY_ERRORS",
  GET_ENTRIES_REQUEST: "GET_ENTRIES_REQUEST",
  GET_ENTRIES_SUCCESS: "GET_ENTRIES_SUCCESS",
  GET_ENTRIES_ERRORS: "GET_ENTRIES_ERRORS",
  DELETE_ENTRY_REQUEST: "DELETE_ENTRY_REQUEST",
  DELETE_ENTRY_SUCCESS: "DELETE_ENTRY_SUCCESS",
  DELETE_ENTRY_ERRORS: "DELETE_ENTRY_ERRORS",
};

export default constants;